---
title: Stel een variabele in met een knop
hero_image: images/banner.png
description: Stel een variabele in met een knop
version: 4
listed: false
copyedit: false
last_tested: "2021-05-12"
steps:
  - title: Inleiding
