title: Set a variable with a button
hero_image: images/banner.png
description: Set a variable with a button
version: 4
listed: false
copyedit: false
last_tested: "2021-05-12"
steps:
  - title: Introduction
