---
title: Gosod newidyn gyda botwm
hero_image: images/banner.png
description: Gosod newidyn gyda botwm
version: 4
listed: false
copyedit: false
last_tested: "2021-05-12"
steps:
  - title: Cyflwyniad
