---
title: Definir uma variável com um botão
hero_image: images/banner.png
description: Definir uma variável com um botão
version: 4
listed: false
copyedit: false
last_tested: "2021-05-12"
steps:
  - 
    title: Introdução
