---
title: Nastav proměnnou pomocí tlačítka
hero_image: images/banner.png
description: Nastav proměnnou pomocí tlačítka
version: 4
listed: false
copyedit: false
last_tested: "2021-05-12"
steps:
  - title: Úvod
