---
title: Fija una variable con un botón
hero_image: images/banner.png
description: Fija una variable con un botón
version: 4
listed: false
copyedit: false
last_tested: "2021-05-12"
steps:
  - 
    title: Introducción
