---
title: Ustaw zmienną za pomocą przycisku
hero_image: images/banner.png
description: Ustaw zmienną za pomocą przycisku
version: 4
listed: false
copyedit: false
last_tested: "2021-05-12"
steps:
  - 
    title: Wprowadzenie
