---
title: Définir une variable avec un bouton
hero_image: images/banner.png
description: Définir une variable avec un bouton
version: 4
listed: false
copyedit: false
last_tested: "2021-05-12"
steps:
  - 
    title: Introduction
