---
title: Imposta una variabile con un pulsante
hero_image: images/banner.png
description: Imposta una variabile con un pulsante
version: 4
listed: false
copyedit: false
last_tested: "2021-05-12"
steps:
  - 
    title: Introduzione
